USE [ASKUE_StavropolEnergo]
GO

/****** Object:  Table [dbo].[t_Departments]    Script Date: 04.12.2017 10:22:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[t_Departments](
	[ID_Department] [int] IDENTITY(1,1) NOT NULL,
	[ID_Branch] [int] NOT NULL,
	[DepartmentName] [varchar](255) NOT NULL,
 CONSTRAINT [PK_t_Departments] PRIMARY KEY CLUSTERED 
(
	[ID_Department] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

