USE [ASKUE_StavropolEnergo]
GO

/****** Object:  Table [dbo].[t_Tasks]    Script Date: 04.12.2017 10:23:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[t_Tasks](
	[ID_Task] [int] IDENTITY(1,1) NOT NULL,
	[ID_Point] [int] NOT NULL,
 CONSTRAINT [PK_t_Tasks] PRIMARY KEY CLUSTERED 
(
	[ID_Task] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

